#pragma once

class CMobTemplate : ZRefCounted {
    unsigned int _ZtlSecureTear_dwTemplateID[2];
    unsigned int _ZtlSecureTear_dwTemplateID_CS;
    unsigned int _ZtlSecureTear_dwLinkedTemplateID[2];
    unsigned int _ZtlSecureTear_dwLinkedTemplateID_CS;
    unsigned int _ZtlSecureTear_dwMonsterBookID[2];
    unsigned int _ZtlSecureTear_dwMonsterBookID_CS;
    ZXString<char> sName;
    int _ZtlSecureTear_nSpecies[2];
    unsigned int _ZtlSecureTear_nSpecies_CS;
    int _ZtlSecureTear_nMoveAbility[2];
    unsigned int _ZtlSecureTear_nMoveAbility_CS;
    int _ZtlSecureTear_bRegenAction[2];
    unsigned int _ZtlSecureTear_bRegenAction_CS;
    int _ZtlSecureTear_bBodyAttack[2];
    unsigned int _ZtlSecureTear_bBodyAttack_CS;
    int _ZtlSecureTear_bBoss[2];
    unsigned int _ZtlSecureTear_bBoss_CS;
    int _ZtlSecureTear_nLevel[2];
    unsigned int _ZtlSecureTear_nLevel_CS;
    int _ZtlSecureTear_nMaxHP[2];
    unsigned int _ZtlSecureTear_nMaxHP_CS;
    int _ZtlSecureTear_nMaxMP[2];
    unsigned int _ZtlSecureTear_nMaxMP_CS;
    int _ZtlSecureTear_nSpeed[2];
    unsigned int _ZtlSecureTear_nSpeed_CS;
    int _ZtlSecureTear_nFlySpeed[2];
    unsigned int _ZtlSecureTear_nFlySpeed_CS;
    int _ZtlSecureTear_nChaseSpeed[2];
    unsigned int _ZtlSecureTear_nChaseSpeed_CS;
    int _ZtlSecureTear_nPAD[2];
    unsigned int _ZtlSecureTear_nPAD_CS;
    int _ZtlSecureTear_nPDR[2];
    unsigned int _ZtlSecureTear_nPDR_CS;
    int _ZtlSecureTear_nMAD[2];
    unsigned int _ZtlSecureTear_nMAD_CS;
    int _ZtlSecureTear_nMDR[2];
    unsigned int _ZtlSecureTear_nMDR_CS;
    int _ZtlSecureTear_nACC[2];
    unsigned int _ZtlSecureTear_nACC_CS;
    int _ZtlSecureTear_nEVA[2];
    unsigned int _ZtlSecureTear_nEVA_CS;
    int _ZtlSecureTear_nEXP[2];
    unsigned int _ZtlSecureTear_nEXP_CS;
    int _ZtlSecureTear_nPushedDamage[2];
    unsigned int _ZtlSecureTear_nPushedDamage_CS;
    int aDamagedElemAttr[8];
    int nHPRecovery;
    int nMPRecovery;
    int _ZtlSecureTear_bUndead[2];
    unsigned int _ZtlSecureTear_bUndead_CS;
    long double nFs;
    int _ZtlSecureTear_bSelfDestruction[2];
    unsigned int _ZtlSecureTear_bSelfDestruction_CS;
    int _ZtlSecureTear_bFirstSelfDestruction[2];
    unsigned int _ZtlSecureTear_bFirstSelfDestruction_CS;
    int _ZtlSecureTear_bPickUpDrop[2];
    unsigned int _ZtlSecureTear_bPickUpDrop_CS;
    int _ZtlSecureTear_bFirstAttack[2];
    unsigned int _ZtlSecureTear_bFirstAttack_CS;
    int _ZtlSecureTear_bInvincible[2];
    unsigned int _ZtlSecureTear_bInvincible_CS;
    int _ZtlSecureTear_bDisable[2];
    unsigned int _ZtlSecureTear_bDisable_CS;
    int bNoFlip;
    int _ZtlSecureTear_bNotAttack[2];
    unsigned int _ZtlSecureTear_bNotAttack_CS;
    int _ZtlSecureTear_nFixedDamage[2];
    unsigned int _ZtlSecureTear_nFixedDamage_CS;
    int _ZtlSecureTear_nWeaponID[2];
    unsigned int _ZtlSecureTear_nWeaponID_CS;
    int _ZtlSecureTear_bAngerGauge[2];
    unsigned int _ZtlSecureTear_bAngerGauge_CS;
    int _ZtlSecureTear_nChargeCount[2];
    unsigned int _ZtlSecureTear_nChargeCount_CS;
    int _ZtlSecureTear_bHPGaugeHide[2];
    unsigned int _ZtlSecureTear_bHPGaugeHide_CS;
    int _ZtlSecureTear_nHPTagColor[2];
    unsigned int _ZtlSecureTear_nHPTagColor_CS;
    int _ZtlSecureTear_nHPTagBgColor[2];
    unsigned int _ZtlSecureTear_nHPTagBgColor_CS;
    int bChase;
    int bDamagedByMob;
    int nDropItemPeriod;
    ZArray<unsigned long> m_aDamagedBySelectedMob;
    int nBanType;
    int nAttackCount;
    int nSkillCount;
    int nHitCount;
    int nDieCount;
    int bHideHP;
    int bHideName;
    int bHideLevel;
    int nEscortType;
    ZRef<MobAttackInfo> m_apAttackInfo[9];
    ZArray<MobSkillInfo> m_aSkillInfo;
    ZArray<ZRef<MobSpeakInformation> > apSpeakInformation;
    ZArray<ZRef<MobSpeakCondition> > apSpeakCondition;
    int nChatBalloon;
    int nWidth;
    int _ZtlSecureTear_bOnlyNormalAttack[2];
    unsigned int _ZtlSecureTear_bOnlyNormalAttack_CS;
    ZArray<long> m_aDamagedBySelectedSkill;
    int bCantPassByTeleport;
    int _ZtlSecureTear_nCategory[2];
    unsigned int _ZtlSecureTear_nCategory_CS;
    int _ZtlSecureTear_bCannotEvade[2];
    unsigned int _ZtlSecureTear_bCannotEvade_CS;
    int _ZtlSecureTear_bUpperMostLayer[2];
    unsigned int _ZtlSecureTear_bUpperMostLayer_CS;
};
