struct ForcedStat {
    int _ZtlSecureTear_nSTR[2];
    unsigned int _ZtlSecureTear_nSTR_CS;
    int _ZtlSecureTear_nDEX[2];
    unsigned int _ZtlSecureTear_nDEX_CS;
    int _ZtlSecureTear_nINT[2];
    unsigned int _ZtlSecureTear_nINT_CS;
    int _ZtlSecureTear_nLUK[2];
    unsigned int _ZtlSecureTear_nLUK_CS;
    int _ZtlSecureTear_nPAD[2];
    unsigned int _ZtlSecureTear_nPAD_CS;
    int _ZtlSecureTear_nPDD[2];
    unsigned int _ZtlSecureTear_nPDD_CS;
    int _ZtlSecureTear_nMAD[2];
    unsigned int _ZtlSecureTear_nMAD_CS;
    int _ZtlSecureTear_nMDD[2];
    unsigned int _ZtlSecureTear_nMDD_CS;
    int _ZtlSecureTear_nACC[2];
    unsigned int _ZtlSecureTear_nACC_CS;
    int _ZtlSecureTear_nEVA[2];
    unsigned int _ZtlSecureTear_nEVA_CS;
    int _ZtlSecureTear_nSpeed[2];
    unsigned int _ZtlSecureTear_nSpeed_CS;
    int _ZtlSecureTear_nJump[2];
    unsigned int _ZtlSecureTear_nJump_CS;
    int _ZtlSecureTear_nSpeedMax[2];
    unsigned int _ZtlSecureTear_nSpeedMax_CS;
};
