# CheckMemoryMapKeys.cmake — MSVC-free completeness check.
# Usage: cmake -DREGION=GMS -DMAJOR=84 -DMINOR=1 -P cmake/CheckMemoryMapKeys.cmake
# (run from the repo root)
if (NOT DEFINED REGION OR NOT DEFINED MAJOR OR NOT DEFINED MINOR)
    message(FATAL_ERROR "Set -DREGION -DMAJOR -DMINOR")
endif()
set(_INFILE  "${CMAKE_CURRENT_LIST_DIR}/../include/memory_map.h.in")
set(_MAPFILE "${CMAKE_CURRENT_LIST_DIR}/../memory_maps/${REGION}/v${MAJOR}_${MINOR}.cmake")
if (NOT EXISTS "${_INFILE}")
    message(FATAL_ERROR "missing ${_INFILE}")
endif()
if (NOT EXISTS "${_MAPFILE}")
    message(FATAL_ERROR "missing ${_MAPFILE}")
endif()
include("${_MAPFILE}")
file(STRINGS "${_INFILE}" _LINES)
set(_KEYS "")
foreach(_LINE IN LISTS _LINES)
    string(REGEX MATCHALL "@([A-Z0-9_]+)@" _MATCHES "${_LINE}")
    foreach(_M IN LISTS _MATCHES)
        string(REGEX REPLACE "^@(.*)@$" "\\1" _K "${_M}")
        list(APPEND _KEYS "${_K}")
    endforeach()
endforeach()
list(REMOVE_DUPLICATES _KEYS)
# BUILD_REGION is supplied by the build invocation (-DBUILD_REGION), not the
# memory map file, so it is not one of the 146 memory-map keys. Exclude it here
# so this standalone check reflects exactly the memory-map key set.
list(REMOVE_ITEM _KEYS BUILD_REGION)
set(_MISSING "")
foreach(_K IN LISTS _KEYS)
    if (NOT DEFINED ${_K})
        list(APPEND _MISSING "${_K}")
    elseif ("${${_K}}" STREQUAL "")
        list(APPEND _MISSING "${_K}")
    endif()
endforeach()
list(LENGTH _KEYS _N)
if (_MISSING)
    string(REPLACE ";" "\n  " _J "${_MISSING}")
    message(FATAL_ERROR "v${MAJOR}.${MINOR} missing/empty keys:\n  ${_J}")
endif()
message(STATUS "OK: all ${_N} keys defined and non-empty for ${REGION} v${MAJOR}.${MINOR}")
