name: Build Snapshot

on:
  push:
    branches:
      - main
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - { region: GMS, major: 83, minor: 1 }
          - { region: GMS, major: 87, minor: 1 }
    name: Build ${{ matrix.config.region }} ${{ matrix.config.major }}.${{ matrix.config.minor }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v2.0.0
      - name: Set up CMake
        run: |
          choco install cmake
        shell: pwsh
      - name: Configure CMake
        run: cmake -B build `
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
          -G "Visual Studio 17" -A Win32 `
          -DBUILD_REGION=${{ matrix.config.region }} `
          -DBUILD_MAJOR_VERSION=${{ matrix.config.major }} `
          -DBUILD_MINOR_VERSION=${{ matrix.config.minor }}
        shell: pwsh
      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - name: Artifact Build
        run: cmake --build build --config ${{env.BUILD_TYPE}} --target package_dlls
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: build/artifacts/
          name: snapshot-${{ matrix.config.region }}-${{ matrix.config.major }}.${{ matrix.config.minor }}
