name: Build Snapshot

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Set up CMake
        run: |
          choco install cmake
        shell: pwsh

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 17" -A Win32

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Artifact Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target package_dlls

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/build/artifacts.tar
          name: artifacts-snapshot