name: Build Snapshot

on:
  push:
    branches: [ main ]

concurrency:
  group: snapshot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Snapshot
    uses: ./.github/workflows/_build.yml
    with:
      build_type: Release
      upload: true
      artifact_prefix: snapshot
