name: Pull Request

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-debug:
    name: Build (Debug)
    uses: ./.github/workflows/_build.yml
    with:
      build_type: Debug
      upload: false
      artifact_prefix: pr-debug

  build-release:
    name: Build (Release)
    uses: ./.github/workflows/_build.yml
    with:
      build_type: Release
      upload: false
      artifact_prefix: pr-release
